ALTER TABLE "Purchase"
  ADD COLUMN IF NOT EXISTS "intermediaryCurrency" TEXT,
  ADD COLUMN IF NOT EXISTS "intermediaryRate" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "shippingCostForeign" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "shippingCostGHS" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "PurchaseItem"
  ADD COLUMN IF NOT EXISTS "unitCostGHS" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "shippingAllocated" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "trueCostPerUnit" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "profitMargin" DOUBLE PRECISION NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS "outletPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
